import 'package:flutter/material.dart';
import 'package:flutterapp/app_fomexapp/generatedlistinfoempresawidget/generated/GeneratedRectangle7Widget5.dart';
import 'package:flutterapp/app_fomexapp/generatedlistinfoempresawidget/generated/GeneratedFrame17Widget1.dart';
import 'package:flutterapp/app_fomexapp/generatedlistinfoempresawidget/generated/GeneratedBtnFinalWidget2.dart';
import 'package:flutterapp/app_fomexapp/generatedlistinfoempresawidget/generated/GeneratedFrame16Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/app_fomexapp/generatedlistinfoempresawidget/generated/GeneratedFrame14Widget1.dart';
import 'package:flutterapp/app_fomexapp/generatedlistinfoempresawidget/generated/GeneratedRectangle7Widget6.dart';
import 'package:flutterapp/app_fomexapp/generatedlistinfoempresawidget/generated/GeneratedFrame15Widget1.dart';

/* Frame listInfoEmpresa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListInfoEmpresaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth;

              final double height = constraints.maxHeight;

              return Stack(children: [
                TransformHelper.translate(
                    x: 0,
                    y: 0,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedRectangle7Widget5(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth;

              final double height = constraints.maxHeight * 0.07511737089201878;

              return Stack(children: [
                TransformHelper.translate(
                    x: 0,
                    y: 0,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedRectangle7Widget6(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: null,
            width: 352.0,
            height: 35.0,
            child: TransformHelper.translate(
                x: 0.50, y: -327.50, z: 0, child: GeneratedFrame14Widget1()),
          ),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: null,
            width: 352.0,
            height: 35.0,
            child: TransformHelper.translate(
                x: 0.50, y: -223.50, z: 0, child: GeneratedFrame15Widget1()),
          ),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: null,
            width: 352.0,
            height: 35.0,
            child: TransformHelper.translate(
                x: 0.50, y: -171.50, z: 0, child: GeneratedFrame17Widget1()),
          ),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: null,
            width: 352.0,
            height: 35.0,
            child: TransformHelper.translate(
                x: 0.50, y: -275.50, z: 0, child: GeneratedFrame16Widget1()),
          ),
          Positioned(
            left: 0.0,
            top: 788.0,
            right: null,
            bottom: null,
            width: 393.0,
            height: 64.0,
            child: GeneratedBtnFinalWidget2(),
          )
        ]),
      ),
    ));
  }
}
