import 'package:flutter/material.dart';
import 'package:flutterapp/app_fomexapp/generatedhomescreenwidget/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/app_fomexapp/generatedhomescreenwidget/generated/GeneratedFrameLojaWidget1.dart';
import 'package:flutterapp/app_fomexapp/generatedhomescreenwidget/generated/GeneratedSlidBarWidget.dart';
import 'package:flutterapp/app_fomexapp/generatedhomescreenwidget/generated/GeneratedFrameLojaWidget.dart';
import 'package:flutterapp/app_fomexapp/generatedhomescreenwidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame homeScreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle2Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.07511737089201878;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup2Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 104.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -252.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.8956743002544529;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.05343511450381679,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedFrameLojaWidget(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: 0.0,
                top: null,
                right: 0.0,
                bottom: null,
                width: null,
                height: 104.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -123.00,
                    z: 0,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width =
                          constraints.maxWidth * 0.8956743002544529;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * 0.05343511450381679,
                            y: 0,
                            z: 0,
                            child: Container(
                              width: width,
                              child: GeneratedFrameLojaWidget1(),
                            ))
                      ]);
                    })),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 625.0,
                height: 36.0,
                child: TransformHelper.translate(
                    x: 116.00,
                    y: -333.00,
                    z: 0,
                    child: GeneratedSlidBarWidget()),
              )
            ]),
      ),
    ));
  }
}
