import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/app_fomexapp/generatedestoqueempresawidget/generated/GeneratedRectangle8Widget4.dart';
import 'package:flutterapp/app_fomexapp/generatedestoqueempresawidget/generated/GeneratedCadEmpresaFieldWidget1.dart';

/* Frame estoqueEmpresa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEstoqueEmpresaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              final double width = constraints.maxWidth;

              final double height = constraints.maxHeight;

              return Stack(children: [
                TransformHelper.translate(
                    x: 0,
                    y: 0,
                    z: 0,
                    child: Container(
                      width: width,
                      height: height,
                      child: GeneratedRectangle8Widget4(),
                    ))
              ]);
            }),
          ),
          Positioned(
            left: null,
            top: null,
            right: null,
            bottom: null,
            width: 319.0,
            height: 626.0,
            child: GeneratedCadEmpresaFieldWidget1(),
          )
        ]),
      ),
    ));
  }
}
