import 'package:flutter/material.dart';
import 'package:flutterapp/app_fomexapp/generatedlistempresaframewidget/generated/GeneratedFrameLojaWidget3.dart';

/* Frame listEmpresaFrame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListEmpresaFrameWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 352.0,
        height: 115.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(0, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 104.0,
                child: GeneratedFrameLojaWidget3(),
              )
            ]),
      ),
    ));
  }
}
