import 'package:flutter/material.dart';
import 'package:flutterapp/app_fomexapp/generatedcadempresawidget/generated/GeneratedCadEmpresaFieldWidget.dart';
import 'package:flutterapp/app_fomexapp/generatedcadempresawidget/generated/GeneratedRectangle3Widget6.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame cadEmpresa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadEmpresaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle3Widget6(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 319.0,
                height: 626.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -28.00,
                    z: 0,
                    child: GeneratedCadEmpresaFieldWidget()),
              )
            ]),
      ),
    ));
  }
}
