import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/app_fomexapp/generatedlistesmpresawidget/generated/GeneratedFrameLojaWidget2.dart';
import 'package:flutterapp/app_fomexapp/generatedlistesmpresawidget/generated/GeneratedBtnFinalWidget1.dart';
import 'package:flutterapp/app_fomexapp/generatedlistesmpresawidget/generated/GeneratedRectangle3Widget9.dart';
import 'package:flutterapp/app_fomexapp/generatedlistesmpresawidget/generated/GeneratedRectangle6Widget4.dart';

/* Frame listEsmpresa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListEsmpresaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 393.0,
        height: 852.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height = constraints.maxHeight;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle3Widget9(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 788.0,
                right: null,
                bottom: null,
                width: 393.0,
                height: 64.0,
                child: GeneratedBtnFinalWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.07511737089201878;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle6Widget4(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 352.0,
                height: 104.0,
                child: TransformHelper.translate(
                    x: 0.50,
                    y: -298.00,
                    z: 0,
                    child: GeneratedFrameLojaWidget2()),
              )
            ]),
      ),
    ));
  }
}
